{% set name = "dials-data" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dials_data/dials_data-{{ version }}.tar.gz
  sha256: c3187b5ea68a1c8dfcaadb37ceb3ac8c7ffc7d6350e5f989f7849257bec43b68

build:
  number: 0
  noarch: python
  entry_points:
    - dials.data = dials_data.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - importlib_resources
    - pytest
    - python
    - pyyaml

test:
  imports:
    - dials_data
  commands:
    - dials.data --help
    - dials.data list

about:
  home: https://github.com/dials/data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: DIALS Regression Data Manager

  description: |
    A python package providing data files used for regression tests in
    scientific software processing crystallographic data, such as DIALS,
    dxtbx, xia2, and related packages.
  doc_url: https://dials-data.readthedocs.io/
  dev_url: https://github.com/dials/data

extra:
  recipe-maintainers:
    - anthchirp
