travis:
  secure:
    BINSTAR_TOKEN: RRhV8JIVMq2BGEbD3CR4Bk1937Yk4TjqQcyrgMEQ8ne0d/NK2Us2z/4bwfPa1/q0gxE6m+zSKEtX+lioPDiBQ6U8Z+UCJoYygYAfCZt7h/f3mcFXn2bNzsyGQ/i2UcZekw1gBpG8CjGv9ReYknjwKj25UD7cMAKdLG/XVj3zEkwE7Lo9Bx/rIRPT2GlJnQtMkrLOX1BVT6x5FhwyaoU363mQr2/qxorPQJrJGZCOR2t7WeDW+n8j+kQSYe8//ywLp4WevxcuW6l31jVjX02Dk6e8ThIjiiaPYMi4NBpuSK8tggOvnmehg/G18Kj+fkQZc2mGRM1NKuthkFmlGwH2gkLBhB8tnbhJftjjmiAMA+CZRY+obqV+kfTTMsQT5EjgXZQSVfC2p/szm0aqFkS/4RBZIOi4jLujP8/EICBHAO6E5U6GWW/Nva85Ny/y1z6Ja5yu5M026zY1yGfMniYe06QDdwUlvWSmcna/t9weHlMva+l0PHx33/fvvVfPUmLhZv4RZItre0CGv6GP24kLlwpSCfuBzRfjG3QTu5GD40uQy6nJUroCYiC71VIL8bNtMtj3o+yrS3yQOCmct+1vMG46k64C+zDPKgy25kfQFKoUB59pOUnJypprwOz9PUZZKuSeNPWpLWkfbTorcP8lTPoW6bdFO7n4hPo+Vp+z4jo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
